# -*- coding: utf-8 -*-
"""tergul 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-odzVNjol3tq7fy492qjqzIOlcQHUfd
"""









import csv
import ipywidgets as widgets
from IPython.display import display

FILE_PATH = "students.txt"  # Directly using the relative path

# Function to read students from file
def read_students():
    students = {}
    try:
        with open(FILE_PATH, mode="r") as file:
            reader = csv.reader(file)
            for row in reader:
                if row:
                    students[row[0]] = row  # Store by first name
    except FileNotFoundError:
        print(f"File not found: {FILE_PATH}. Please make sure the file exists.")
    return students

# Function to write students to file
def write_students(students):
    try:
        with open(FILE_PATH, mode="w", newline="") as file:
            writer = csv.writer(file)
            for student in students.values():
                writer.writerow(student)
    except Exception as e:
        print(f"Error saving file: {e}")

# Load student data
students_data = read_students()

# Create dropdown to select student
student_dropdown = widgets.Dropdown(
    options=list(students_data.keys()),
    description="Student:"
)

# Create text fields
first_name_text = widgets.Text(description="First Name:")
last_name_text = widgets.Text(description="Last Name:")
email_text = widgets.Text(description="Email:")
courses_text = widgets.Text(description="Courses:")
link_text = widgets.Text(description="Link:")

# Function to display selected student details
def display_student_details(change):
    selected_name = student_dropdown.value
    if selected_name:
        student_details = students_data[selected_name]

        first_name_text.value = student_details[0]
        last_name_text.value = student_details[1]
        email_text.value = student_details[2]
        courses_text.value = student_details[3]
        link_text.value = student_details[4]

# Function to update student data and save to file
def update_student_data(b):
    selected_name = student_dropdown.value
    if selected_name:
        students_data[selected_name] = [
            first_name_text.value,
            last_name_text.value,
            email_text.value,
            courses_text.value,
            link_text.value
        ]
        write_students(students_data)  # Save changes to file
        print(f"✅ Data for {selected_name} updated successfully and saved to file!")

# Attach event listener
student_dropdown.observe(display_student_details, names="value")

# Create update button
update_button = widgets.Button(description="Update Data", button_style="success")
update_button.on_click(update_student_data)

# Display widgets
display(student_dropdown, first_name_text, last_name_text, email_text, courses_text, link_text, update_button)

# Initialize first student display
display_student_details(None)